export default {
  //Post
  GET_LIST_ALL_POSTS: 'GET_LIST_ALL_POSTS',
  GET_LIST_ALL_POSTS_ERROR: 'GET_LIST_ALL_POSTS_ERROR',
  GET_LIST_ALL_POSTS_SUCCESS: 'GET_LIST_ALL_POSTS_SUCCESS',

  GET_RETRIEVE_A_POST: 'GET_RETRIEVE_A_POST',
  GET_RETRIEVE_A_POST_ERROR: 'GET_RETRIEVE_A_POST_ERROR',
  GET_RETRIEVE_A_POST_SUCCESS: 'GET_RETRIEVE_A_POST_SUCCESS',

  POST_CREATE_POST: 'POST_CREATE_POST',
  POST_CREATE_POST_ERROR: 'POST_CREATE_POST_ERROR',
  POST_CREATE_POST_SUCCESS: 'POST_CREATE_POST_SUCCESS',

  PUT_UPDATE_A_POST: 'PUT_UPDATE_A_POST',
  PUT_UPDATE_A_POST_ERROR: 'PUT_UPDATE_A_POST_ERROR',
  PUT_UPDATE_A_POST_SUCCESS: 'PUT_UPDATE_A_POST_SUCCESS',

  DEL_DELETE_A_POST: 'DEL_DELETE_A_POST',
  DEL_DELETE_A_POST_ERROR: 'DEL_DELETE_A_POST_ERROR',
  DEL_DELETE_A_POST_SUCCESS: 'DEL_DELETE_A_POST_SUCCESS',

  //Comment
  POST_CREATE_A_COMMENT: 'POST_CREATE_POST',
  POST_CREATE_A_COMMENT_ERROR: 'POST_CREATE_A_COMMENT_ERROR',
  POST_CREATE_A_COMMENT_SUCCESS: 'POST_CREATE_A_COMMENT_SUCCESS',
}
